version: 2

project_name: gotmpl

before:
  hooks:
    - go mod tidy

builds:
  - ldflags:
      - -s -w -X github.com/jtyr/{{ .ProjectName }}/pkg/version.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    main: ./cmd/{{ .ProjectName }}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" -}}
        x86_64
      {{- else if eq .Arch "386" -}}
        i386
      {{- else }}
        {{- .Arch }}
      {{- end }}
      {{- if .Arm -}}
        v{{ .Arm }}
      {{- end }}
